#trigger is master 
trigger:
- main


pool:
  vmImage: ubuntu-latest



steps:
- script: echo Hello, Terraform single app!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  displayName: download secretkey
  name: publicKey
  inputs:
    secureFile: 'rsa.pub'


- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_files'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(e40c9fbc-48e9-4ae3-9f40-5c33d3c6cfd5)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'single-app-resource-grp'
    backendAzureRmResourceGroupLocation: 'Central US'
    backendAzureRmStorageAccountName: 'singleappstogae'
    backendAzureRmContainerName: 'singleappcontainer'
    backendAzureRmKey: 'terraform.tfstate'


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
  
- task: PythonScript@0
  inputs:
    scriptSource: "inline"
    script: |
      import os
      os.system("terraform plan")


