#trigger is master 
trigger:
- main


pool:
  vmImage: ubuntu-latest



steps:
- script: echo Hello, Terraform single app!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  displayName: download secretkey
  name: publicKey
  inputs:
    secureFile: 'id_rsa.pub'


- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform_files'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial(e40c9fbc-48e9-4ae3-9f40-5c33d3c6cfd5)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'single-app-resource-grp'
    backendAzureRmResourceGroupLocation: 'Central US'
    backendAzureRmStorageAccountName: 'singleappstogae'
    backendAzureRmContainerName: 'singleappcontainer'
    backendAzureRmKey: 'terraform.tfstate'




- task: CmdLine@2
  displayName: Terraform apply
  inputs:
    script: 'terraform apply -var $(client_id) -var $(client_secret) -var $(publicKey.secureFilePath)'