#trigger is master 
trigger:
- main


pool:
  vmImage: ubuntu-latest



steps:
- script: echo Hello, Terraform single app!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'id_rsa.pub'


- task: CmdLine@2
  displayName: Terraform initilize
  inputs:
    script: 'echo terraform init'
    workingDirectory: 'https://github.com/Parshchakurkar/single-app/tree/main/terraform_files'



