#trigger is master 
trigger:
- main


pool:
  vmImage: ubuntu-latest



steps:
- script: echo Hello, Terraform single app!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'id_rsa.pub'


- task: CmdLine@2
  displayName: change directory to wroking directory
  inputs:
    script: |
      echo cd /mnt/c/Devops/terraform_files
      echo terraform int
    workingDirectory: '/mnt/c/Devops/terraform_files'



